sudo: required
dist: trusty
script: make ICEBOX=/usr/local/share/icebox/ test
language: cpp
addons:
  apt:
    packages:
    - build-essential
    - libftdi-dev
    - llvm-3.6
    - gcc-4.8
    - git
    - python
    - python3
before_install:
# get yosys via a PPA (since compiling it takes a while !)
  - sudo add-apt-repository -y ppa:saltmakrell/ppa
  - sudo apt-get -y update
  - sudo apt-get -y install yosys
# Build icestorm from get master (for an up-to-date chipdb)
  - sudo apt-get -y install git
  - git clone https://github.com/cliffordwolf/icestorm.git
  - cd icestorm && make
  - sudo make install
  - cd -
os: linux
compiler:
  - gcc
  - clang
branches:
  except:
    - dummy
