sudo: required
dist: trusty
script: make ICEBOX=/usr/local/share/icebox/ test
language: cpp
addons:
  apt:
    packages:
    - build-essential
    - libftdi-dev
    - llvm-3.6
    - gcc-4.8
    - git
    - python
    - python3
before_install:
  - sudo apt-get -y update
  - sudo apt-get -y install git
  - echo test
  - pwd
  - git clone https://github.com/cliffordwolf/icestorm.git
  - cd icestorm
  #&& make && sudo make install
  - pwd
  - cd -
  - pwd
os: linux
compiler:
  - gcc
  - clang
branches:
  except:
    - dummy
